image: node:10.11.0

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'>.npmrc
    - npm install
    - npm run packagr
    - npm pack dist/
    - npm publish Inobeta-inobeta-ui-$CURRENT_VERSION.tgz --tag latest
  only:
    - master
deploy_unstable:
  stage: deploy
  script:
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'>.npmrc
    - create_temp_version
    - npm install
    - npm run packagr
    - npm pack dist/
    - npm publish Inobeta-inobeta-ui-$CURRENT_VERSION-$CI_COMMIT_SHA.tgz --tag unstable
  except:
    - master
.inobeta_pkg: &inobeta_pkg |
  [[ "$TRACE" ]] && set -x

  function create_temp_version() {
      CURRENT_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')
      sed -i "s/\"version\"\: \"$CURRENT_VERSION\"/\"version\": \"$CURRENT_VERSION-$CI_COMMIT_SHA\"/g" ./package.json
      echo $CURRENT_VERSION-$CI_COMMIT_SHA
  }

before_script:
  - *inobeta_pkg
