image: node:10.11.0

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'>.npmrc
    - npm publish --tag stable
  only:
    - master
deploy_unstable:
  stage: deploy
  script:
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'>.npmrc
    - npm version --no-git-tag-version prerelease --preid=$CI_COMMIT_SHA
    - npm publish --tag unstable
  except:
    - master
